spring:
  application:
    name: VendingMachineDemo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/VendingMachineDemo?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver